version: 0.2

phases:
  install:
    # Install dependencies like Terraform
    runtime-versions:
      terraform: 1.3 # Specify the Terraform version to install
    commands:
      - echo "Installing Terraform..."
      - terraform --version

  pre_build:
    # Initialize Terraform and set environment variables if needed
    commands:
      - echo "Initializing Terraform..."
      - terraform init # Initialize Terraform project

  build:
    # Run Terraform plan to preview changes
    commands:
      - echo "Running Terraform plan..."
      - terraform plan -out=tfplan # Output plan to a file

  post_build:
    # Apply the Terraform configuration
    commands:
      - echo "Applying Terraform plan..."
      - terraform apply -input=false -auto-approve tfplan # Apply the plan

artifacts:
  files:
    - tfplan